### ISSUE TITLE
'rasa run actions' missing

### ISSUE THREAD

**Issue by LarissaHa** [RasaHQ/breakoutbot#5]
When trying to run the bot, apart from `rasa train` the command `rasa run actions` is necessary. 
This should be included to the README :)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Good catch. It's clearly explained in the videos but not here. 

@LarissaHa you're free to do a PR if you'd like. That way you'd also unlock the github committer achievement. If you need a bit of help navigating: let me know! If you're busy, also fine 👍

**Comment by LarissaHa** [comment]
okay thanks @koaning ! I'll try, this will be my first time contributing to another project on github 😬 If I do something stupid or wrong, please tell me 🙈

**Comment by koaning** [comment]
I'd say this went smoothly. Thanks!
